### PR TITLE
Function specification for bootstrapping and CI

### PR DESCRIPTION
**Pull request by gauthampughazhendhi**
Function specification for bootstrapping and CI

### CODE REVIEW

**Comment by BooleanJulien** [comment]
@gauthampughazhendhi in generating the bootsrapped distributions, can we have a default for "n" (size of each bootstrap sample) be "auto" ?

This would be the length of the input vector/column by default. 

Otherwise looks good!

**Comment by gauthampughazhendhi** [comment]
@BooleanJulien sure, that's a good suggesstion. I will update my PR.

**Comment by gauthampughazhendhi** [comment]
@BooleanJulien update my PR, you can find the change now.

**Comment by BooleanJulien** [comment]
technically @zackt113 needs to approve still I believe? If everything looks good you can merge!

**Comment by zackt113** [comment]
Yeah, everything looks good. But for the second function, I think the data type of the parameter "level" be float? @gauthampughazhendhi Other than that, looks perfect!

**Comment by gauthampughazhendhi** [comment]
@zackt113 made the change, thanks for the intimation. You can merge the PR now.

**Comment by zackt113** [comment]
Great, merged it.

**Pull request merged**
