### PR TITLE
Adding function descriptions to readme

### PR DESCRIPTION
**Pull request by BooleanJulien**
Used @gauthampughazhendhi and @zackt113's function descriptions to update the readme. I believe the readme is now done for this milestone.

### CODE REVIEW

**Comment by gauthampughazhendhi** [comment]
@BooleanJulien one quick suggestion, you may need to update once after Zack's change on the last function's name since it's going to be more stats.
One general thing I noticed is that the source branch is not a feature branch. I think it's your fork's dev branch, for this project you can directly work on the UBC MDS straPy repo with feature branches. You may not need to fork.

**Comment by BooleanJulien** [comment]
Good points @gauthampughazhendhi! I will use a feature branch next week, I totally forgot!

**Comment by voremargot** [comment]
This looks good to me! Zack if you like how it looks go ahead and merge the pull request.

**Comment by zackt113** [comment]
Looks good to me, will merge!

**Pull request merged**
